version: '3.8'

services: 

  mysqldb:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: csp
    ports:
      - 3306:3306
    volumes: 
      - ./.db:/var/lib/mysql
    networks: 
      - local
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    ports: 
      - 3000:3000
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    networks: 
      - local

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks: 
      - local
  
    

networks:
  local:
    driver: bridge